# Uncomment the next line to define a global platform for your project
# platform :osx, '10.11'

target 'TCPSerwver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TCPSerwver
  pod 'SwiftSocket'
  target 'TCPSerwverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TCPSerwverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
